version: "3.7"
services:
  nuxt:
    image: ghcr.io/${GITHUB_ACTOR}/frontend-deploy-nuxt:latest
    container_name: frontend-deploy-nuxt
    command: "npm run start"
    ports:
      - "3000:3000"
    environment:
      - MAIN_API_URL=${NUXT_PUBLIC_MAIN_API_URL}
      - AI_BASE_URL=${NUXT_PUBLIC_AI_BASE_URL}
      - TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - KAKAO_NATIVE_APP_KEY=${KAKAO_NATIVE_APP_KEY}
      - KAKAO_JAVASCRIPT_APP_KEY=${KAKAO_JAVASCRIPT_APP_KEY}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    restart: always
    networks:
      - app

  nginx:
    image: "nginx:latest"
    container_name: frontend-deploy-nginx
    restart: unless-stopped
    volumes:
      - /home/ec2-user/snack/nuxt/frontend/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
    external: true